version: "3"

services:
  bitcoind:
    restart: unless-stopped
    build:
      context: ./Dockerfiles
      dockerfile: bitcoin
    image: joemphilips/bitcoind
    environment:
      BITCOIN_NETWORK: regtest
    user: root:root
    command:
      - bitcoind
      - -datadir=/data
      - -regtest
      - -rpcauth=${BITCOIND_RPC_AUTH}
      - -rpcport=43782
      - -rpcbind=0.0.0.0:43782
      - -rpcallowip=0.0.0.0/0
      - -port=39388
      - -txindex=1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
      - -deprecatedrpc=signrawtransaction
      - -assumevalid=00000000000000000012d0c0982d818aa909d78e54525b10563c698d89997632
      - -maxmempool=500 # MB
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
    volumes:
      - "${DATADIR_ROOT}/.bitcoin:/data"
  lnd_alice:
    restart: unless-stopped
    image: joemphilips/lnd
    build:
      context: ./Dockerfiles
      dockerfile: lnd
    entrypoint: ["./start-lnd.sh"]
    environment:
      NETWORK: regtest
    command:
      - --restlisten=0.0.0.0:32736
      - --rpclisten=0.0.0.0:32777
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:43782
      - --bitcoind.rpcuser=${BITCOIND_RPC_USER}
      - --bitcoind.rpcpass=${BITCOIND_RPC_PASS}
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --trickledelay=1000
      - --externalip=lnd_alice:9735
        #- --no-macaroons
      - --datadir=/data
      - --debuglevel=debug
        # - --noseedbackup
      - --tlscertpath=/data/tls.cert
      - --tlskeypath=/data/tls.key
      - --tlsextradomain=lnd_alice
    expose:
      - "9735"
      - "32736"
      - "32777"
    volumes:
      - "${DATADIR_ROOT}/.lnd_alice:/data"
      - "${DATADIR_ROOT}/.bitcoin:/deps/.bitcoin"
  lnd_bob:
    restart: unless-stopped
    image: joemphilips/lnd
    build:
      context: ./Dockerfiles
      dockerfile: lnd
    entrypoint: ["./start-lnd.sh"]
    environment:
      NETWORK: regtest
    command:
      - --restlisten=0.0.0.0:32737
      - --rpclisten=0.0.0.0:32778
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:43782
      - --bitcoind.rpcuser=${BITCOIND_RPC_USER}
      - --bitcoind.rpcpass=${BITCOIND_RPC_PASS}
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --trickledelay=1000
      - --externalip=lnd_bob:9735
        #- --no-macaroons
      - --datadir=/data
      - --debuglevel=debug
        # - --noseedbackup
      - --tlscertpath=/data/tls.cert
      - --tlskeypath=/data/tls.key
      - --tlsextradomain=lnd_bob
    expose:
      - "9735"
      - "32737"
      - "32778"
    volumes:
      - "${DATADIR_ROOT}/.lnd_bob:/data"
      - "${DATADIR_ROOT}/.bitcoin:/deps/.bitcoin"
