version: "3"

services:
  bitcoind:
    restart: unless-stopped
    build:
      context: ./Dockerfiles
      dockerfile: bitcoin
    image: joemphilips/bitcoind
    environment:
      BITCOIN_NETWORK: regtest
    user: root:root
    command:
      - bitcoind
      - -datadir=/data
      - -wallet=cashcow
      - -regtest
      - -rpcauth=${BITCOIND_RPC_AUTH}
      - -rpcport=43782
      - -rpcbind=0.0.0.0:43782
      - -rpcallowip=0.0.0.0/0
      - -port=39388
      - -txindex=1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
      - -deprecatedrpc=signrawtransaction
      - -assumevalid=00000000000000000012d0c0982d818aa909d78e54525b10563c698d89997632
      - -maxmempool=500 # MB
      - -fallbackfee=0.0001
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
    volumes:
      - "${DATADIR_ROOT}/.bitcoin:/data"
  lnd_alice:
    restart: unless-stopped
    image: joemphilips/lnd
    build:
      context: ./Dockerfiles
      dockerfile: lnd
    entrypoint: ["./start-lnd.sh"]
    environment:
      NETWORK: regtest
    depends_on:
      - bitcoind
    command:
      - --restlisten=0.0.0.0:32736
      - --rpclisten=0.0.0.0:32777
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:43782
      - --bitcoind.rpcuser=${BITCOIND_RPC_USER}
      - --bitcoind.rpcpass=${BITCOIND_RPC_PASS}
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --trickledelay=1000
      - --externalip=lnd_alice:9735
        #- --no-macaroons
      - --datadir=/data
      - --debuglevel=debug,PEER=info
        # - --noseedbackup
      - --tlscertpath=/data/tls.cert
      - --tlskeypath=/data/tls.key
      - --tlsextradomain=lnd_alice
    expose:
      - "9735"
      - "32736"
      - "32777"
    ports:
      - "32777:32777"
    volumes:
      - "${DATADIR_ROOT}/.lnd_alice:/data"
      - "${DATADIR_ROOT}/.bitcoin:/deps/.bitcoin"

  loopd:
    image: joemphilips/loopd:v0.14.2-beta
    build:
      context: ./Dockerfiles
      dockerfile: loopd
      args:
        - LOOPD_VERSION=v0.14.2-beta
    restart: unless-stopped
    volumes:
      - "${DATADIR_ROOT}/.lnd_alice:/root/.lnd"
    depends_on:
      - lnd_alice
    command:
      - "loopd"
      - "--network=regtest"
      - "--debuglevel=debug"
      - "--server.host=loopserver:11009"
      - "--server.notls"
      - "--lnd.host=lnd_alice:32777"
      - "--lnd.macaroonpath=/root/.lnd/chain/bitcoin/regtest/admin.macaroon"
      - "--lnd.tlspath=/root/.lnd/tls.cert"
    expose:
      - "8081" # server
      - "11010" # rpc

  lnd_bob:
    restart: unless-stopped
    image: joemphilips/lnd
    build:
      context: ./Dockerfiles
      dockerfile: lnd
    entrypoint: ["./start-lnd.sh"]
    environment:
      NETWORK: regtest
    depends_on:
      - bitcoind
    command:
      - --restlisten=0.0.0.0:32737
      - --rpclisten=0.0.0.0:32778
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:43782
      - --bitcoind.rpcuser=${BITCOIND_RPC_USER}
      - --bitcoind.rpcpass=${BITCOIND_RPC_PASS}
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --trickledelay=1000
      - --externalip=lnd_bob:9735
        #- --no-macaroons
      - --datadir=/data
      - --debuglevel=debug,PEER=info
        # - --noseedbackup
      - --tlscertpath=/data/tls.cert
      - --tlskeypath=/data/tls.key
      - --tlsextradomain=lnd_bob
    expose:
      - "9735"
      - "32737"
      - "32778"
    ports:
      - "32778:32778"
    volumes:
      - "${DATADIR_ROOT}/.lnd_bob:/data"
      - "${DATADIR_ROOT}/.bitcoin:/deps/.bitcoin"
  boltz:
    image: boltz/regtest:3.1.0
    restart: unless-stopped
    build:
      context: ./Dockerfiles
      dockerfile: boltz
    command:
      - "--configpath=/data/boltz/boltz.conf"
    expose:
      - "9000" # grpc API
    ports:
      - "9001:9001" # REST API
    volumes:
      - "${DATADIR_ROOT}/boltz:/data/boltz"
      - "${DATADIR_ROOT}/.lnd_bob:/data/lnd"
    depends_on:
      - bitcoind
    links:
      - "bitcoind"
      - "lnd_bob"

  lnd_carol:
    restart: unless-stopped
    image: joemphilips/lnd
    build:
      context: ./Dockerfiles
      dockerfile: lnd
    entrypoint: ["./start-lnd.sh"]
    environment:
      NETWORK: regtest
    depends_on:
      - bitcoind
    command:
      - --restlisten=0.0.0.0:32737
      - --rpclisten=0.0.0.0:32779
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:43782
      - --bitcoind.rpcuser=${BITCOIND_RPC_USER}
      - --bitcoind.rpcpass=${BITCOIND_RPC_PASS}
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --trickledelay=1000
      - --externalip=lnd_carol:9735
        #- --no-macaroons
      - --datadir=/data
      - --debuglevel=debug,PEER=info
        # - --noseedbackup
      - --tlscertpath=/data/tls.cert
      - --tlskeypath=/data/tls.key
      - --tlsextradomain=lnd_carol
    expose:
      - "9735"
      - "32737"
      - "32779"
    ports:
      - "32779:32779"
    volumes:
      - "${DATADIR_ROOT}/.lnd_carol:/data"
      - "${DATADIR_ROOT}/.bitcoin:/deps/.bitcoin"
  loopserver:
    image: lightninglabs/loopserver:v0.8.2-beta
    restart: unless-stopped
    volumes:
      - "${DATADIR_ROOT}/.lnd_carol:/root/.lnd"
    depends_on:
      - lnd_carol
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--lnd.host=lnd_carol:32779"
      - "--lnd.macaroondir=/root/.lnd/chain/bitcoin/regtest"
      - "--lnd.tlspath=/root/.lnd/tls.cert"

  clightning_alice:
    restart: unless-stopped
    image: joemphilips/lightningd
    build:
      context: ./Dockerfiles
      dockerfile: lightning
      args:
        LIGHTNINGD_VERSION: "v0.10.1"
    environment:
      EXPOSE_TCP: "true"
      LIGHTNINGD_NETWORK: regtest
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_PORT: 9735
      LIGHTNINGD_RPC_PORT: 9835
      LIGHTNINGD_ANNOUNCEADDR: clightning_alice
      LIGHTNINGD_DATA: /root/.lightning
    command:
      - "--network=regtest"
      - "--lightning-dir=/root/.lightning"
      - "--allow-deprecated-apis=false"
      - "--bitcoin-datadir=/deps/.bitcoin"
      - "--bitcoin-rpcuser=${BITCOIND_RPC_USER}"
      - "--bitcoin-rpcpassword=${BITCOIND_RPC_PASS}"
      - "--bitcoin-rpcconnect=bitcoind"
      - "--bitcoin-rpcport=43782"
      # - "--plugin-dir=/plugins"
      # - "--plugin=/root/.lightning/plugins/summary"
      # - "--plugin=/opt/lightningd/plugins/summary"
    depends_on:
      - bitcoind
    volumes:
      - "clightning_alice:/root/.lightning"
      - "${DATADIR_ROOT}/bitcoin:/deps/.bitcoin"
    expose:
      - "9735"
    ports:
      - "9835:9835"

volumes:
  loopserver:
  loopd:
  clightning_alice:

